### DISCUSSION TITLE
an idea: use com.unity.package-manager.metadata and verdaccio uplinks

### DISCUSSION THREAD

**Discussion by mob-sakai** [openupm/openupm#61] [Ideas]
### Profit:

Users can access all packages in OpenUpm simply by adding the following to `manifest.json`:

```
"registry" : "https://package.openupm.com",
```

The `scopedRegistories` field are no longer required.

---

### Use package `com.unity.package-manager.metadata`

I noticed that UPM was listed based on a simple package.
The package contains a list of all packages searchable in the UI.
https://packages.unity.com/com.unity.package-manager.metadata
https://download.packages.unity.com/com.unity.package-manager.metadata/-/com.unity.package-manager.metadata-0.0.77.tgz

Can you publish a `com.unity.package-manager.metadata` package to OpenUpm?

* `com.unity.package-manager.metadata` contains a list of all packages in official registry and all packages in OpenUpm
* `com.unity.package-manager.metadata` should be updated automatically

In this way, users can use OpenUpm instead of the Unity official package registry.

---

### Use verdaccio uplinks:

verdaccio has a feature called `uplinks`.
https://verdaccio.org/docs/en/uplinks

* Packages that do not exist in OpenUpm can be found using an external registry.
* For example, `com.unity.*` packages should come from Unity official package registry.

Edit the verdaccio configuration file `config.yml` as follows.
```
uplinks:
  unity:
    url: https://packages.unity.com

packages:

  'com.unity.package-manager.metadata':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  'com.unity.*':
    access: $all
    proxy: unity

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'unity' registry
    proxy: unity
```

---

### Note

* I tested the idea locally and it seems to be working
* I am not an expert on npm registries or verdaccio
