### ISSUE TITLE
Update Medium post part-1 and workflow gist/example

### ISSUE THREAD

**Issue by Chizaruu** [openupm/openupm#4163]
## Feature request
Update [Medium post part-1](https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4) and [workflow gist](https://gist.github.com/favoyang/c365762ed844fae2d6d97be08e64f654#file-ci-yml)/example
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [x] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [ ] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [x] Documentation
- [x] Others

#### What problem does this feature solve?
Deprecation of workflow
#### How should this be implemented in your opinion?
Because it's going to break [soon](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/).
#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?
No
#### Are you willing to work on this yourself?
Here have some code.

```yml
name: CI
on:
    push:
        branches:
            - default
jobs:
    split-upm:
        name: split upm branch
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3 # specify the version to v3
              with:
                  fetch-depth: 0
            - name: split upm branch
              run: |
                  git subtree split -P "$PKG_ROOT" -b upm
                  git push -u origin upm
              env:
                  PKG_ROOT: Packages/package-name
```
